### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by Serg-Norseman** [elistia/DotNetRtfWriter#1]
There are three questions: how difficult is it to add support for internal links and the generation of the two-column text? And supporting of lists?

**Comment by elistia** [comment]
~~Hi - I think that all of these should be possible and would be happy to look in to this.  Any of the three you are particulary interested in? :-)~~

Apologies, just spotted your pull request (been away for a few days).  Will take a look.

**Comment by elistia** [comment]
Serg, many thanks for your contribution.  All merged.  I will try to take a look at the columns/lists when I get a chance. If you want to start work on these yourself then please do, just let me know so we don't duplicate effort.  I will close this issue and start two new ones for columns and lists.

**Comment by elistia** [comment]
http://www.lexjansen.com/pharmasug/2006/technicaltechniques/tt21.pdf

**Comment by Serg-Norseman** [comment]
While I did only hyperlinks and only internal. First, because only they were needed. And secondly, at that time, was in a hurry for my project, and have not delved into the architecture of this library. I didn't want to make mass edits, not knowing the intricacies and the suitable places of introduction.

**Comment by Serg-Norseman** [comment]
In my project, I made lists using the simulation (marker symbol + tab). It's not very good, was going to deal with this issue later. But not enough time.

**Comment by Serg-Norseman** [comment]
If were possible to create a two-column text with automatic breakdown, then I would be able to rid in my project from buggy pdf-generators under Linux.
