### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by dwhuang** [elistia/DotNetRtfWriter#3]
I am the original author of .NET RTF Writer on SourceForge who came across this page accidentally. It is a pleasure to see that someone resurrected the project I started almost a decade ago! Unfortunately I haven't had a chance to work in .NET since then. So the project stayed at v0.9 for a looong time, and after Matt and Thomson (who I know by email) jumped in and added a few features, I decided to just call it v1.0 and had left it there. 

Sorry that you couldn't contact me via SourceForge -- my old email must be dead.

Anyway, just wanted to let you know I'm very glad that someone is keeping this project alive.

**Comment by elistia** [comment]
Hi - Thanks so much for getting in touch!

The work you did is very much appreciated and has helped me a lot so am trying to give a bit back if possible by keeping it maintained.
